### ISSUE TITLE
SXGA RGB image support for AsusXtionProLive

### ISSUE THREAD

**Issue by alireza-hosseini** [ros-drivers/openni_camera#1]
I am using Asus Xtion Pro Live Sensor and the openni_camera for my project,
The issue is when i reconfigure openni_node to publish RGB images with SXGA resolution using dynamic_reconfigure_gui it gives us following warning and RGB image keeps publishing with 640x480 resolution:

[ WARN] [1349881911.100499691]: Could not find any compatible image output mode for 1280 x 1024 @ 15. Falling back to default image output mode 640 x 480 @ 30.

I have tested the capability of publishing SXGA RGB images from ASUS XTION PRO LIVE using NiViewer Sample of Openni library and it works properly. So i am pretty sure that SXGA RGB image is supported by Asus Xtion Pro live and also openni driver.

BTW: I am using ROS fuerte.

**Comment by jonbinney** [comment]
Hmm... I'm not able to view the xtion image with /usr/bin/NiViewer in the openni-utils package. When I run it i get:

```
jbinney@bih-> /usr/bin/NiViewer 
Open failed: Bad Parameter sent to the device!
Press any key to continue . . .
```

Is that the executable you use to view SXGA resolution images from the xtion? Could you run "dpkg -l|grep openni" and post the result so I can make sure we have that same versions of things?

**Comment by alireza-hosseini** [comment]
Actually i have got the the same error using the recent openni (1.5.4.0-3+precise1) and sensor(5.1.0.41-2+precise1) packages from ROS repository.So I manually installed OpenNI-Bin-Dev-Linux-x64-v1.5.2.23  and Sensor-Bin-Linux-x64-v5.1.0.41 downloaded from Openni Github and the problem solved. NiViewer worked properly and also SXGA RGB image resolution Viewed successfully.
It seems that libopenni-sensor-primesense0 package(or maybe libopenni0 ?) in the ROS repository is especially configured for Microsoft Kinect according to its description:
"Microsoft Kinect sensor modules for the OpenNI framework"
So with no doubt Openni driver supports SXGA image resolution for Asus Xtion Pro Live.

**Comment by jonbinney** [comment]
The openni packages in the ros repos are patched to work with the kinect, but also work with the xtion.  As you've noticed though, they don't support SXGA resolution.  I'll try this tomorrow with the openni packages from github.

**Comment by jonbinney** [comment]
I managed to get SXGA images from the Xtion, but to do so I had to change formats and have the Openni drivers output RGB24 instead of YUV422. For some reason this seems to have broken the VGA and QVGA resolution outputs.

**Comment by jonbinney** [comment]
Here are the changes needed to make openni_camera do SXGA resolution with the xtion: https://gist.github.com/4508201

It's not stable enough to apply to the repo and release (for example it breaks the VGA and QVGA modes), but maybe being able to compile from source will be enough for you.  A proper fix would require more changes; for instance it would probably require some logic to have the xtion output YUV422 images for VGA and RGB24 images for SXGA. I'm inclined to wait, since openni is releasing version 2.0 of their library, which is substantially different and which we will hopefully be moving to soon.

If you want to tackle the task of properly reworking openni_camera to handle SXGA without breaking the other modes, I'd be happy to merge it :-)

**Comment by alireza-hosseini** [comment]
Thanks a lot jon, i think only SXGA RGB image would be enough for my project, but of course i would be glad to help you in fixing the code. I will do my best to handle SXGA along with other image modes, actually i need some time to read and understand the logic of the code. I will keep you posted ;-)

**Comment by jonbinney** [comment]
I'm going to go ahead and close this issue since I don't plan on adding this in anytime soon. If you get it working reliably, reopen as a pull request.

**Comment by jkammerl** [comment]
Note that the openni2_camera package does support SXGA RGB streaming:
https://github.com/ros-drivers/openni2_camera
