### ISSUE TITLE
OpenNi2-Camera

### ISSUE THREAD

**Issue by hcw70** [ros-drivers/openni_camera#15]
Hi. 

Are there any plans to port OpenNi-Camera to OpenNi2?

This would be needed for RaspberryPi esp. since there the OpenNi2 runs well while OpenNi does not. See https://groups.google.com/forum/#!topic/ros-sig-arm/6XgbkvnL3GM for some details.

Regards Hauke

**Comment by jkammerl** [comment]
Hi Hauke,

yes, it is on my list! I'll keep updated.

Cheers, 
Julius

**Comment by jkammerl** [comment]
Your'll find the openni2_camera package here:
https://github.com/ros-drivers/openni2_camera

As soon as the openni2 debians are available within ROS, I'll trigger an official deb release.

**Comment by bit-pirate** [comment]
Which version of Nite will come with it?

**Comment by jonbinney** [comment]
Openni_camera2 doesn't include any version of Nite; it's just a ROS driver for getting sensor data from an xtion.

**Comment by bit-pirate** [comment]
True, I realised that, when test-driving openni2. :-)
I have to look into the openni_tracker then.
Thanks for the info!

**Comment by bit-pirate** [comment]
Btw, could you guess, when the openni2 debs (camera and launch) will be available? Will you release them into Groovy as well?

**Comment by jonbinney** [comment]
It looks like it's already out. If you have the ros repos and you do

```
sudo apt-get install libopenni2-0 libopenni2-dev
```

you should be able to get them and give openni2_camera a try. It's pretty untested and might not yet have all the features that openni_camera had, but It'd be great to have people start trying it.

**Comment by bit-pirate** [comment]
I already did that and it's running smoothly. :-) Nice job!
Just wondering when the ROS debs will be available.

2013/6/21 jonbinney notifications@github.com

> It looks like it's already out. If you have the ros repos and you do
> 
> sudo apt-get install libopenni2-0 libopenni2-dev
> 
> you should be able to get them and give openni2_camera a try. It's pretty
> untested and might not yet have all the features that openni_camera had,
> but It'd be great to have people start trying it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-drivers/openni_camera/issues/15#issuecomment-19800307
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by jonbinney** [comment]
I can release it into hydro in the next  couple weeks, but I don't have much time to maintain or implement missing features, so pull requests will be welcome :-)

**Comment by bit-pirate** [comment]
Fair enough! A release would be nice.
We probably will have a person here testing and working with it, so we might can give something back.

I'm a bit greedy though: could we also get it for Groovy? :)

**Comment by jonbinney** [comment]
Yeah, you're probably right that we should also release into groovy as well. I started on this today, but got blocked by a library path problem. I've created a ticket for doing the release here: https://github.com/ros-drivers/openni2_camera/issues/11

**Comment by Rouno** [comment]
Dear Jon, here is something I found interesting and that might help you : http://computervisionblog.wordpress.com/2013/06/09/hands-on-capri-building-an-openni2-ros-interface/

This guy managed to have a capri sensor (new tiny kinect) and set openni 2 up in ros.

Best regards
