### ISSUE TITLE
Push 1.9.4 into ROS indigo/jade

### ISSUE THREAD

**Issue by jspricke** [ros-drivers/openni_camera#42]
Hi,

could you please push 1.9.4 into ROS indigo and jade? It only fixes the dependency issue and should be save to push.

Thanks!

Jochen

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/10077 and https://github.com/ros/rosdistro/pull/10078.

Looks like I tagged a release awhile ago but didn't push to rosdistro, don't know why.
