### ISSUE TITLE
Noetic release request

### ISSUE THREAD

**Issue by knorth55** [ros-drivers/openni_camera#77]
@130s 
Thank you for this useful package.
Are there any plan to release this package in Noetic?
If you have no time, I can help you for noetic release.

**Comment by 130s** [comment]
Thank you for the headsup. Release of 1.6.0 is made on openni2_camera side.
.deb generation is requested in https://github.com/ros/rosdistro/pull/32739
Closing for now.

**Comment by 130s** [comment]
I'm sorry https://github.com/ros-drivers/openni_camera/issues/77#issuecomment-1096551058 was about openni2. Re-opening.

@knorth55 If you have verified the functionality of the pkgs on this repo on ROS noetic, wolud you mind opening a PR, had there been any code change needed to get it working? I just made `ros1` branch off of `indigo-devel`, which I intend to use as the main development branch for ROS Melodic and Noetic.

**Comment by 130s** [comment]
@knorth55 On a separate note, I added a maintainer right on this repo. Thank you for stepping up! Feel free to add yourself in `package.xml`.

**Comment by knorth55** [comment]
@130s thank you! I will check for noetic!

**Comment by knorth55** [comment]
I checked with the current branch, and it works in Noetic + Kinect.
![Screenshot from 2022-04-13 22-08-00](https://user-images.githubusercontent.com/9300063/163187272-12627174-0f27-4355-9d77-f90f1bcde34c.png)

**Comment by knorth55** [comment]
@130s can you change the default branch from `indigo-devel` to `ros1` and give access to `ros-gbp/openni_camera-release`?
https://github.com/ros-gbp/openni_camera-release

**Comment by knorth55** [comment]
Thanks to #67, python3 is already supported.

**Comment by 130s** [comment]
Thank you!  Because of the confirmation you made, I don't feel a necessity to cut another version release on this repo. What's needed instead is to publish into a new ROS distro i.e. Noetic, which is requested https://github.com/ros/rosdistro/pull/32783 (using `bloom`).

> can you change the default branch from indigo-devel to ros1 and give access to ros-gbp/openni_camera-release? https://github.com/ros-gbp/openni_camera-release

Done and done.

**Comment by knorth55** [comment]
You released the current version in Noetic! Perfect! Thank you!!
